// Generated by Wrangler on Tue Jul 09 2024 16:11:23 GMT+0700 (Western Indonesia Time)
// by running `wrangler types`

interface Env {
	BLUESKY_IDENTIFIER: string;
	BLUESKY_PASSWORD: string;
	BLUESKY_SERVICE: string;
}
